### ISSUE TITLE
method_deprecated /api/rtm.start

### ISSUE THREAD

**Issue by spurin** [orliesaurus/greetingslack#28]
Hi all,

Deployed this today on a newly built workspace, getting the following method_deprecated warning.  Any ideas anyone please?

```
2022-06-19T17:16:28.816798+00:00 app[worker.1]: DEBUG:urllib3.connectionpool:https://slack.com:443 "GET /api/rtm.start?token=<removed> HTTP/1.1" 200 60
2022-06-19T17:16:28.817507+00:00 app[worker.1]: INFO:root:{'ok': False, 'error': 'method_deprecated'}
2022-06-19T17:16:28.817545+00:00 app[worker.1]: Traceback (most recent call last):
2022-06-19T17:16:28.817555+00:00 app[worker.1]:   File "/app/bot.py", line 116, in <module>
2022-06-19T17:16:28.817684+00:00 app[worker.1]:     r = start_rtm()
2022-06-19T17:16:28.817686+00:00 app[worker.1]:   File "/app/bot.py", line 99, in start_rtm
2022-06-19T17:16:28.817765+00:00 app[worker.1]:     r = r["url"]
2022-06-19T17:16:28.817785+00:00 app[worker.1]: KeyError: 'url'
2022-06-19T17:16:28.930236+00:00 heroku[worker.1]: Process exited with status 1
2022-06-19T17:16:29.062921+00:00 heroku[worker.1]: State changed from up to crashed
```

**Comment by spurin** [comment]
Looks like it's related to this - https://api.slack.com/changelog/2021-10-rtm-start-to-stop

Am guessing that most existing users may have signed up prior to November 2021 -

_"Beginning today, you'll see method_deprecated warnings returned by rtm.start. After November 30, 2021, newly created apps will see the warning migrate to a method_deprecated error."_

**Comment by spurin** [comment]
Had a play around and this seems to be working locally for me with a simple change 

```
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): slack.com:443
DEBUG:urllib3.connectionpool:https://slack.com:443 "GET /api/rtm.connect?token=<removed> HTTP/1.1" 200 298
INFO:root:{'ok': True, 'url': '<removed>', 'team': {'id': '<removd>', 'name': '<removed>', 'domain': '<removed>'}, 'self': {'id': '<removed>', 'name': 'greetingbot'}}
{'type': 'hello', 'fast_reconnect': False, 'region': 'eu-west-2', 'start': True, 'host_id': 'gs-lhr-wc-wpfl'}
```

Have raised 2 merge requests for your convenience -

1. Just the fix: https://github.com/orliesaurus/greetingslack/pull/29
2. The fix, alongside with formatting (using black) and documentation updates (for Python 2.7 and 3 instructions)

Very much appreciate your open source efforts! Thank you!!

**Comment by orliesaurus** [comment]
Thank you! Merged your work in, this was very useful!
