### ISSUE TITLE
r["url"] issue

### ISSUE THREAD

**Issue by feesh** [orliesaurus/greetingslack#4]
Hi there! First off thanks so much for creating and sharing this! Super useful bot. :)

I followed the guide on [this Medium article](https://medium.com/@izzydoesizzy/create-a-slack-bot-that-privately-greets-new-users-in-5-easy-steps-a38eabeabcb5) but am stuck after the deploy step. Here are the errors I get in the Heroku logs. A friend of mine tried as well on her Slack team and ran into the same problem. Did I miss a configuration step?

```2017-06-07T20:00:43.569234+00:00 heroku[worker.1]: State changed from crashed to starting
2017-06-07T20:00:47.258569+00:00 heroku[worker.1]: Starting process with command `python bot.py`
2017-06-07T20:00:47.896677+00:00 heroku[worker.1]: State changed from starting to up
2017-06-07T20:00:50.362696+00:00 app[worker.1]: Traceback (most recent call last):
2017-06-07T20:00:50.362718+00:00 app[worker.1]:   File "bot.py", line 58, in <module>
2017-06-07T20:00:50.362761+00:00 app[worker.1]:     r = start_rtm()
2017-06-07T20:00:50.362763+00:00 app[worker.1]:   File "bot.py", line 41, in start_rtm
2017-06-07T20:00:50.362793+00:00 app[worker.1]:     r = r["url"]
2017-06-07T20:00:50.362830+00:00 app[worker.1]: KeyError: 'url'
2017-06-07T20:00:50.478606+00:00 heroku[worker.1]: State changed from up to crashed
2017-06-07T20:00:50.464249+00:00 heroku[worker.1]: Process exited with status 1```

**Comment by orliesaurus** [comment]
Hello @feesh ok, go in  `https://dashboard.heroku.com/apps/YOUR-APP-ID/settings`
please add a Config Variable:
`UNFURL-LINKS`
and its value

**Comment by feesh** [comment]
Thank you!! That worked!

**Comment by alockerman** [comment]
@feesh how did you set it all up? When i tried setting it up using the article, I could even scale the worker to 1... any ideas?
